import http from 'node:http';
import crypto from 'node:crypto';
import {URL} from 'node:url';
import pg from 'pg';
const PORT=Number(process.env.PORT||10000),ADMIN_KEY=process.env.ADMIN_KEY||'',DATABASE_URL=process.env.DATABASE_URL||'',ALLOWED_ORIGIN=process.env.ALLOWED_ORIGIN||'*';
const SHOP={brand:process.env.SHOP_BRAND||'ORDER CATALOG',sub:process.env.SHOP_SUB||'เลือกสินค้า • ขนาด • ฝา • จำนวน',contact:process.env.SHOP_CONTACT||'',shippingFee:Number(process.env.SHIPPING_FEE||50),freeShippingMin:Number(process.env.FREE_SHIPPING_MIN||0)};
const DEFAULT_FILTERS={groups:[{id:'style',label:'สไตล์',options:['เน้นรุก','เน้นรับ','รุกและรับ']},{id:'strength',label:'ความฉุน',options:['ฉุนมาก','ฉุนน้อย']}]};
const mem={products:[],orders:new Map(),filters:structuredClone(DEFAULT_FILTERS)};let pool=DATABASE_URL?new pg.Pool({connectionString:DATABASE_URL,ssl:{rejectUnauthorized:false}}):null;
const clean=s=>String(s??'').trim();
function json(res,code,body){res.writeHead(code,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':ALLOWED_ORIGIN,'access-control-allow-headers':'content-type,x-admin-key','access-control-allow-methods':'GET,POST,PUT,PATCH,OPTIONS'});res.end(JSON.stringify(body))}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',d=>{s+=d;if(s.length>2e6)reject(new Error('payload too large'))});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}});req.on('error',reject)})}
function auth(req){return !!ADMIN_KEY&&req.headers['x-admin-key']===ADMIN_KEY}
function normalizeProduct(p){return {...p,id:clean(p.id),name:clean(p.name),image:clean(p.image),tags:p.tags&&typeof p.tags==='object'?p.tags:{},stockTracked:!!p.stockTracked,stock:{'10ml':Number(p.stock?.['10ml']||0),'30ml':Number(p.stock?.['30ml']||0)},lowStockThreshold:Number(p.lowStockThreshold??5)}}
function dedupe(list){const seenId=new Set(),seenNameImage=new Set(),out=[];for(const raw of list){const p=normalizeProduct(raw),id=p.id.toLowerCase(),ni=(p.name.toLowerCase().replace(/\s+/g,' ')+'|'+p.image.toLowerCase());if(seenId.has(id)||seenNameImage.has(ni))continue;seenId.add(id);seenNameImage.add(ni);out.push(p)}return out}
function baseProducts(){return Array.from({length:295},(_,i)=>{const n=i+1,id=`p${String(n).padStart(3,'0')}`;return normalizeProduct({id,name:`สินค้า ${String(n).padStart(3,'0')}`,image:`products/${id}.jpg`,active:true,sizes:['10ml','30ml'],caps:['ฝาแดง','ฝาดำ'],prices:{'10ml':{retail:490,wholesale:450},'30ml':{retail:850,wholesale:790}},wholesaleMin:6,stockTracked:false,stock:{'10ml':0,'30ml':0},lowStockThreshold:5,tags:{}})})}
async function init(){mem.products=baseProducts();if(!pool)return;try{await pool.query(`create table if not exists products(id text primary key,data jsonb not null,updated_at timestamptz default now());create table if not exists orders(id text primary key,data jsonb not null,created_at timestamptz default now(),updated_at timestamptz default now());create table if not exists settings(key text primary key,data jsonb not null,updated_at timestamptz default now());`);const c=Number((await pool.query('select count(*)::int n from products')).rows[0].n||0);if(!c){for(const p of mem.products)await pool.query('insert into products(id,data) values($1,$2) on conflict(id) do nothing',[p.id,p])}const fr=await pool.query("select data from settings where key='filters'");if(fr.rowCount)mem.filters=fr.rows[0].data}catch(e){console.error('DB init failed',e.message);pool=null}}
async function products(){if(pool){const r=await pool.query('select data from products order by id');return dedupe(r.rows.map(x=>x.data))}return dedupe(mem.products)}
async function saveProduct(p){p=normalizeProduct(p);if(pool)await pool.query('insert into products(id,data,updated_at) values($1,$2,now()) on conflict(id) do update set data=$2,updated_at=now()',[p.id,p]);else{const i=mem.products.findIndex(x=>x.id===p.id);if(i>=0)mem.products[i]=p;else mem.products.push(p)}return p}
async function saveFilters(v){const groups=(v.groups||[]).map(g=>({id:clean(g.id).replace(/[^a-zA-Z0-9_-]/g,''),label:clean(g.label),options:[...new Set((g.options||[]).map(clean).filter(Boolean))]})).filter(g=>g.id&&g.label);mem.filters={groups};if(pool)await pool.query("insert into settings(key,data,updated_at) values('filters',$1,now()) on conflict(key) do update set data=$1,updated_at=now()",[mem.filters]);return mem.filters}
function priceFor(p,size,qty){const pr=p.prices?.[size]||{retail:0,wholesale:0};return Number(qty>=Number(p.wholesaleMin||0)?pr.wholesale:pr.retail)||0}
function shippingFor(subtotal,method){if(method==='pickup')return 0;return SHOP.freeShippingMin>0&&subtotal>=SHOP.freeShippingMin?0:Math.max(0,SHOP.shippingFee)}
function orderId(){const d=new Date(),y=String(d.getFullYear()).slice(-2),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `OD${y}${m}${day}-${crypto.randomBytes(5).toString('hex').slice(0,8).toUpperCase()}`}
async function createOrder(input){const ps=await products(),by=new Map(ps.map(p=>[p.id,p])),groups=new Map();for(const raw of input.items||[]){const id=clean(raw.productId),size=clean(raw.size),qty=Math.max(1,Math.floor(Number(raw.qty)||1)),cap=clean(raw.cap),k=id+'|'+size,g=groups.get(k)||{id,size,qty:0,lines:[]};g.qty+=qty;g.lines.push({qty,cap});groups.set(k,g)}if(!groups.size)throw Object.assign(new Error('ไม่มีสินค้าในออเดอร์'),{status:400});let subtotal=0;const items=[];for(const g of groups.values()){const p=by.get(g.id);if(!p||p.active===false)throw Object.assign(new Error('ไม่พบสินค้า'),{status:400});const stock=Number(p.stock?.[g.size]||0);if(p.stockTracked&&g.qty>stock)throw Object.assign(new Error(`${p.name} ${g.size} คงเหลือ ${stock} ชิ้น`),{status:409});const unit=priceFor(p,g.size,g.qty);for(const l of g.lines){const total=unit*l.qty;subtotal+=total;items.push({id:crypto.randomUUID(),productId:p.id,name:p.name,image:p.image,size:g.size,cap:l.cap,qty:l.qty,unit,total,priceType:g.qty>=Number(p.wholesaleMin||0)?'ส่ง':'ปลีก'})}if(p.stockTracked){p.stock[g.size]=stock-g.qty;await saveProduct(p)}}const method=input.customer?.deliveryMethod==='pickup'?'pickup':'delivery',fee=shippingFor(subtotal,method),id=clean(input.id)||orderId(),now=new Date().toISOString();const order={id,createdAt:now,customer:{name:clean(input.customer?.name),contact:clean(input.customer?.contact),address:method==='delivery'?clean(input.customer?.address):'',deliveryMethod:method,note:clean(input.customer?.note)},seller:SHOP.brand,items,itemCount:items.reduce((a,b)=>a+b.qty,0),subtotal,shipping:{method,address:method==='delivery'?clean(input.customer?.address):'',fee,carrier:'',trackingNo:''},total:subtotal+fee,status:'pending',paymentStatus:'unpaid',inventoryReserved:true,inventoryDeducted:true};if(pool)await pool.query('insert into orders(id,data) values($1,$2)',[id,order]);else mem.orders.set(id,order);return order}
async function getOrder(id){if(pool){const r=await pool.query('select data from orders where id=$1',[id]);return r.rowCount?r.rows[0].data:null}return mem.orders.get(id)||null}
await init();
http.createServer(async(req,res)=>{if(req.method==='OPTIONS')return json(res,204,{});try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/health')return json(res,200,{ok:true,version:'2.3.0',storage:pool?'postgres':'memory',products:(await products()).length});if(u.pathname==='/api/shop'&&req.method==='GET')return json(res,200,SHOP);if(u.pathname==='/api/products'&&req.method==='GET')return json(res,200,await products());if(u.pathname==='/api/filter-config'&&req.method==='GET')return json(res,200,mem.filters);if(u.pathname==='/api/orders'&&req.method==='POST'){const b=await body(req);if(!b.customer?.name||!b.customer?.contact)return json(res,400,{error:'กรุณากรอกชื่อและข้อมูลติดต่อ'});return json(res,201,await createOrder(b))}const om=u.pathname.match(/^\/api\/orders\/([^/]+)$/);if(om&&req.method==='GET'){const o=await getOrder(decodeURIComponent(om[1]));if(!o)return json(res,404,{error:'ไม่พบออเดอร์'});const {customer,items,...pub}=o;return json(res,200,pub)}if(u.pathname==='/api/admin/filter-config'&&req.method==='GET'){if(!auth(req))return json(res,401,{error:'unauthorized'});return json(res,200,mem.filters)}if(u.pathname==='/api/admin/filter-config'&&req.method==='PUT'){if(!auth(req))return json(res,401,{error:'unauthorized'});return json(res,200,await saveFilters(await body(req)))}if(u.pathname==='/api/admin/products'&&req.method==='GET'){if(!auth(req))return json(res,401,{error:'unauthorized'});return json(res,200,await products())}const pm=u.pathname.match(/^\/api\/admin\/products\/([^/]+)$/);if(pm&&req.method==='PATCH'){if(!auth(req))return json(res,401,{error:'unauthorized'});const id=decodeURIComponent(pm[1]),ps=await products(),p=ps.find(x=>x.id===id);if(!p)return json(res,404,{error:'ไม่พบสินค้า'});const b=await body(req);if(b.tags&&typeof b.tags==='object')p.tags=b.tags;if(typeof b.active==='boolean')p.active=b.active;return json(res,200,await saveProduct(p))}return json(res,404,{error:'not found'})}catch(e){console.error(e);return json(res,e.status||500,{error:e.message||'server error'})}}).listen(PORT,()=>console.log(`Order Catalog API v2.3 on ${PORT}; storage=${pool?'postgres':'memory'}`));
