import http from 'node:http';
import crypto from 'node:crypto';
import { URL } from 'node:url';
import pg from 'pg';

const PORT=Number(process.env.PORT||10000);
const ADMIN_KEY=process.env.ADMIN_KEY||'';
const CATALOG_URL=process.env.CATALOG_URL||'https://order-catalog-v22-fixed.onrender.com/catalog.json';
const DATABASE_URL=process.env.DATABASE_URL||'';
const ALLOWED_ORIGIN=process.env.ALLOWED_ORIGIN||'*';
const API_BASE=process.env.API_BASE||'https://order-catalog-api-v22.onrender.com';
const DEFAULT_SHOP={brand:process.env.SHOP_BRAND||'ORDER CATALOG',sub:process.env.SHOP_SUB||'เลือกสินค้า • ขนาด • ฝา • จำนวน',contact:process.env.SHOP_CONTACT||'',shippingFee:Number(process.env.SHIPPING_FEE||50),freeShippingMin:Number(process.env.FREE_SHIPPING_MIN||0),wholesaleMinTotal:Number(process.env.WHOLESALE_MIN_TOTAL||20)};
const DEFAULT_FILTERS={groups:[{id:'style',label:'สไตล์',options:['เน้นรุก','เน้นรับ','รุกและรับ']},{id:'strength',label:'ความฉุน',options:['ฉุนมาก','ฉุนน้อย']}]};
const mem={products:[],orders:new Map(),settings:new Map([['shop',DEFAULT_SHOP],['filter_config',DEFAULT_FILTERS]]),images:new Map(),loaded:false};
let pool=null;
if(DATABASE_URL) pool=new pg.Pool({connectionString:DATABASE_URL,ssl:{rejectUnauthorized:false}});

function json(res,code,body,extra={}){const data=JSON.stringify(body);res.writeHead(code,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':ALLOWED_ORIGIN,'access-control-allow-headers':'content-type,x-admin-key','access-control-allow-methods':'GET,POST,PATCH,PUT,DELETE,OPTIONS',...extra});res.end(data)}
function isAdmin(req){return !!ADMIN_KEY&&req.headers['x-admin-key']===ADMIN_KEY}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',d=>{s+=d;if(s.length>4_000_000){reject(Object.assign(new Error('payload too large'),{status:413}));req.destroy()}});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(Object.assign(e,{status:400}))}});req.on('error',reject)})}
function n(v,d=0){const x=Number(v);return Number.isFinite(x)?x:d}
function cleanProduct(p){const q={...p};q.id=String(q.id||'');q.name=String(q.name||q.id||'สินค้า');q.active=q.active!==false;q.sizes=Array.isArray(q.sizes)&&q.sizes.length?q.sizes:['10ml','30ml'];q.caps=Array.isArray(q.caps)&&q.caps.length?q.caps:['ฝาแดง','ฝาดำ'];q.prices=q.prices||{'10ml':{retail:490,wholesale:450},'30ml':{retail:850,wholesale:790}};for(const s of q.sizes)q.prices[s]={retail:n(q.prices?.[s]?.retail),wholesale:n(q.prices?.[s]?.wholesale)};q.stockTracked=!!q.stockTracked;q.stock={'10ml':n(q.stock?.['10ml']),'30ml':n(q.stock?.['30ml'])};q.lowStockThreshold=n(q.lowStockThreshold,5);q.tags=q.tags&&typeof q.tags==='object'?q.tags:{};return q}
function orderId(){const d=new Date(),y=String(d.getFullYear()).slice(-2),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `OD${y}${m}${day}-${crypto.randomBytes(5).toString('hex').slice(0,8).toUpperCase()}`}
function normalizeGroups(input){const arr=Array.isArray(input?.groups)?input.groups:[];const ids=new Set(),groups=[];for(const raw of arr){const id=String(raw.id||'').trim().replace(/[^a-zA-Z0-9_-]/g,'').slice(0,40);if(!id||ids.has(id))continue;ids.add(id);groups.push({id,label:String(raw.label||id).trim().slice(0,60),options:[...new Set((Array.isArray(raw.options)?raw.options:[]).map(x=>String(x).trim()).filter(Boolean))].slice(0,50)})}return{groups}}

async function loadCatalog(){if(mem.loaded)return;try{const r=await fetch(CATALOG_URL,{cache:'no-store'}),ct=r.headers.get('content-type')||'';if(!r.ok||!ct.includes('json'))throw new Error(`catalog ${r.status}`);mem.products=(await r.json()).map(cleanProduct)}catch(e){console.warn('Catalog unavailable, built-in fallback:',e.message);mem.products=Array.from({length:295},(_,i)=>{const id=`p${String(i+1).padStart(3,'0')}`;return cleanProduct({id,name:`สินค้า ${String(i+1).padStart(3,'0')}`,image:`https://order-catalog-v22-fixed.onrender.com/products/${id}.jpg`,active:true,sizes:['10ml','30ml'],caps:['ฝาแดง','ฝาดำ'],prices:{'10ml':{retail:490,wholesale:450},'30ml':{retail:850,wholesale:790}},stockTracked:false,stock:{'10ml':0,'30ml':0},lowStockThreshold:5,tags:{}})})}mem.loaded=true}
async function initDb(){if(!pool)return;await pool.query(`CREATE TABLE IF NOT EXISTS products(id text primary key,data jsonb not null,updated_at timestamptz default now());CREATE TABLE IF NOT EXISTS orders(id text primary key,data jsonb not null,created_at timestamptz default now(),updated_at timestamptz default now());CREATE TABLE IF NOT EXISTS settings(key text primary key,data jsonb not null,updated_at timestamptz default now());CREATE TABLE IF NOT EXISTS product_images(id text primary key,mime text not null,data bytea not null,updated_at timestamptz default now());`);const pn=n((await pool.query('select count(*)::int n from products')).rows[0].n);if(!pn){await loadCatalog();const c=await pool.connect();try{await c.query('begin');for(const p of mem.products)await c.query('insert into products(id,data) values($1,$2) on conflict(id) do nothing',[p.id,p]);await c.query('commit')}catch(e){await c.query('rollback');throw e}finally{c.release()}}await pool.query('insert into settings(key,data) values($1,$2) on conflict(key) do nothing',['shop',DEFAULT_SHOP]);await pool.query('insert into settings(key,data) values($1,$2) on conflict(key) do nothing',['filter_config',DEFAULT_FILTERS])}
async function setting(key,fallback){if(pool){const r=await pool.query('select data from settings where key=$1',[key]);return r.rowCount?r.rows[0].data:fallback}return mem.settings.get(key)||fallback}
async function saveSetting(key,data){if(pool)await pool.query('insert into settings(key,data,updated_at) values($1,$2,now()) on conflict(key) do update set data=excluded.data,updated_at=now()',[key,data]);else mem.settings.set(key,data);return data}
async function shop(){const s=await setting('shop',DEFAULT_SHOP);return{...DEFAULT_SHOP,...s,shippingFee:n(s.shippingFee,DEFAULT_SHOP.shippingFee),freeShippingMin:n(s.freeShippingMin),wholesaleMinTotal:Math.max(1,Math.floor(n(s.wholesaleMinTotal,DEFAULT_SHOP.wholesaleMinTotal)))}}
async function products(){if(pool){const r=await pool.query('select data from products order by id');return r.rows.map(x=>cleanProduct(x.data))}await loadCatalog();return mem.products.map(cleanProduct)}
async function productById(id,client=null){if(client||pool){const c=client||pool,r=await c.query('select data from products where id=$1',[id]);return r.rowCount?cleanProduct(r.rows[0].data):null}await loadCatalog();return cleanProduct(mem.products.find(x=>String(x.id)===String(id))||{})}
async function saveProduct(p){p=cleanProduct(p);if(!p.id)throw Object.assign(new Error('รหัสสินค้าไม่ถูกต้อง'),{status:400});if(pool)await pool.query('insert into products(id,data,updated_at) values($1,$2,now()) on conflict(id) do update set data=excluded.data,updated_at=now()',[p.id,p]);else{await loadCatalog();const i=mem.products.findIndex(x=>String(x.id)===p.id);if(i>=0)mem.products[i]=p;else mem.products.push(p)}return p}
async function deleteProduct(id){const p=await productById(id);if(!p?.id)throw Object.assign(new Error('ไม่พบสินค้า'),{status:404});if(pool){const c=await pool.connect();try{await c.query('begin');await c.query('delete from product_images where id=$1',[id]);await c.query('delete from products where id=$1',[id]);await c.query('commit')}catch(e){await c.query('rollback');throw e}finally{c.release()}}else{await loadCatalog();mem.products=mem.products.filter(x=>String(x.id)!==String(id));mem.images.delete(id)}return{ok:true,id}}
async function bulkPrices(input){const pricePatch=input?.prices||{},activeOnly=!!input?.activeOnly;const allowed=['10ml','30ml'];let updated=0;if(pool){const c=await pool.connect();try{await c.query('begin');const r=await c.query('select id,data from products order by id for update');for(const row of r.rows){const p=cleanProduct(row.data);if(activeOnly&&p.active===false)continue;for(const size of allowed){const x=pricePatch[size];if(!x||!p.sizes.includes(size))continue;p.prices[size]={retail:Math.max(0,n(x.retail,p.prices[size]?.retail)),wholesale:Math.max(0,n(x.wholesale,p.prices[size]?.wholesale))}}await c.query('update products set data=$2,updated_at=now() where id=$1',[p.id,p]);updated++}await c.query('commit')}catch(e){await c.query('rollback');throw e}finally{c.release()}}else{await loadCatalog();for(let i=0;i<mem.products.length;i++){const p=cleanProduct(mem.products[i]);if(activeOnly&&p.active===false)continue;for(const size of allowed){const x=pricePatch[size];if(!x||!p.sizes.includes(size))continue;p.prices[size]={retail:Math.max(0,n(x.retail,p.prices[size]?.retail)),wholesale:Math.max(0,n(x.wholesale,p.prices[size]?.wholesale))}}mem.products[i]=p;updated++}}return{ok:true,updated}}
async function saveProductImage(id,mime,b64){if(!/^image\/(jpeg|png|webp)$/.test(mime))throw Object.assign(new Error('รองรับ JPG, PNG, WEBP เท่านั้น'),{status:400});const buf=Buffer.from(String(b64||''),'base64');if(!buf.length||buf.length>1_500_000)throw Object.assign(new Error('รูปต้องมีขนาดไม่เกิน 1.5MB หลังย่อภาพ'),{status:400});if(pool)await pool.query('insert into product_images(id,mime,data,updated_at) values($1,$2,$3,now()) on conflict(id) do update set mime=excluded.mime,data=excluded.data,updated_at=now()',[id,mime,buf]);else mem.images.set(id,{mime,data:buf});const p=await productById(id);if(!p?.id)throw Object.assign(new Error('ไม่พบสินค้า'),{status:404});p.image=`${API_BASE}/api/product-images/${encodeURIComponent(id)}?v=${Date.now()}`;return saveProduct(p)}
async function imageById(id){if(pool){const r=await pool.query('select mime,data from product_images where id=$1',[id]);return r.rowCount?r.rows[0]:null}return mem.images.get(id)||null}
function shippingFor(s,subtotal,method){if(method==='pickup')return 0;return n(s.freeShippingMin)>0&&subtotal>=n(s.freeShippingMin)?0:Math.max(0,n(s.shippingFee))}

async function createOrder(input){const ps=await products(),byId=new Map(ps.map(p=>[p.id,p])),groups=new Map();let orderQty=0;for(const raw of input.items||[]){const id=String(raw.productId||''),size=String(raw.size||''),qty=Math.max(1,Math.floor(n(raw.qty,1))),cap=String(raw.cap||'');orderQty+=qty;const k=id+'|'+size,g=groups.get(k)||{id,size,qty:0,lines:[]};g.qty+=qty;g.lines.push({qty,cap});groups.set(k,g)}if(!groups.size)throw Object.assign(new Error('ไม่มีสินค้าในออเดอร์'),{status:400});const s=await shop(),isWholesale=orderQty>=s.wholesaleMinTotal,finalItems=[];let subtotal=0;for(const g of groups.values()){const p=byId.get(g.id);if(!p||p.active===false)throw Object.assign(new Error(`ไม่พบสินค้า ${g.id}`),{status:400});if(!p.sizes.includes(g.size))throw Object.assign(new Error(`ขนาดไม่ถูกต้อง: ${p.name}`),{status:400});const stock=n(p.stock?.[g.size]);if(p.stockTracked&&g.qty>stock)throw Object.assign(new Error(`${p.name} ${g.size} คงเหลือ ${stock} ชิ้น`),{status:409});const pr=p.prices[g.size]||{retail:0,wholesale:0},unit=n(isWholesale?pr.wholesale:pr.retail);for(const line of g.lines){const total=unit*line.qty;subtotal+=total;finalItems.push({id:crypto.randomUUID(),productId:p.id,name:p.name,image:p.image,size:g.size,cap:line.cap,qty:line.qty,unit,total,priceType:isWholesale?'ส่ง':'ปลีก'})}}
const method=input.customer?.deliveryMethod==='pickup'?'pickup':'delivery',fee=shippingFor(s,subtotal,method),id=String(input.id||orderId()),now=new Date().toISOString();const order={id,createdAt:now,customer:{name:String(input.customer?.name||''),contact:String(input.customer?.contact||''),address:method==='delivery'?String(input.customer?.address||''):'',deliveryMethod:method,note:String(input.customer?.note||'')},seller:s.brand,items:finalItems,itemCount:orderQty,pricingTier:isWholesale?'wholesale':'retail',wholesaleMinTotal:s.wholesaleMinTotal,subtotal,shipping:{method,address:method==='delivery'?String(input.customer?.address||''):'',fee,carrier:'',trackingNo:''},total:subtotal+fee,status:'pending',paymentStatus:'unpaid',inventoryReserved:true,inventoryDeducted:true};
if(pool){const c=await pool.connect();try{await c.query('begin');for(const g of groups.values()){const r=await c.query('select data from products where id=$1 for update',[g.id]);if(!r.rowCount)throw Object.assign(new Error('สินค้าไม่พบ'),{status:400});const p=cleanProduct(r.rows[0].data),stock=n(p.stock?.[g.size]);if(p.stockTracked&&g.qty>stock)throw Object.assign(new Error(`${p.name} ${g.size} คงเหลือ ${stock} ชิ้น`),{status:409});if(p.stockTracked){p.stock[g.size]=stock-g.qty;await c.query('update products set data=$2,updated_at=now() where id=$1',[g.id,p])}}await c.query('insert into orders(id,data) values($1,$2)',[id,order]);await c.query('commit')}catch(e){await c.query('rollback');throw e}finally{c.release()}}else{for(const g of groups.values()){const p=mem.products.find(x=>x.id===g.id);if(p?.stockTracked)p.stock[g.size]=Math.max(0,n(p.stock?.[g.size])-g.qty)}mem.orders.set(id,order)}return order}
async function getOrder(id){if(pool){const r=await pool.query('select data from orders where id=$1',[id]);return r.rowCount?r.rows[0].data:null}return mem.orders.get(id)||null}
async function listOrders(){if(pool){const r=await pool.query('select data from orders order by created_at desc limit 200');return r.rows.map(x=>x.data)}return [...mem.orders.values()].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,200)}
async function setStatus(id,status){if(!['pending','packing','shipped','done','cancelled'].includes(status))throw Object.assign(new Error('สถานะไม่ถูกต้อง'),{status:400});const o=await getOrder(id);if(!o)throw Object.assign(new Error('ไม่พบออเดอร์'),{status:404});o.status=status;o.updatedAt=new Date().toISOString();if(pool)await pool.query('update orders set data=$2,updated_at=now() where id=$1',[id,o]);else mem.orders.set(id,o);return o}

await loadCatalog();try{await initDb()}catch(e){console.error('DB init failed; memory mode:',e.message);pool=null}

const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS')return json(res,204,{});try{const u=new URL(req.url,'http://localhost');
if(u.pathname==='/health')return json(res,200,{ok:true,version:'2.5.0',storage:pool?'postgres':'memory',products:(await products()).length});
if(u.pathname==='/api/shop'&&req.method==='GET')return json(res,200,await shop());
if(u.pathname==='/api/filter-config'&&req.method==='GET')return json(res,200,await setting('filter_config',DEFAULT_FILTERS));
if(u.pathname==='/api/products'&&req.method==='GET')return json(res,200,await products());
const im=u.pathname.match(/^\/api\/product-images\/([^/]+)$/);if(im&&req.method==='GET'){const pic=await imageById(decodeURIComponent(im[1]));if(!pic)return json(res,404,{error:'image not found'});res.writeHead(200,{'content-type':pic.mime,'cache-control':'public,max-age=86400','access-control-allow-origin':ALLOWED_ORIGIN});return res.end(pic.data)}
if(u.pathname==='/api/orders'&&req.method==='POST'){const input=await body(req);if(!input.customer?.name||!input.customer?.contact)return json(res,400,{error:'กรุณากรอกชื่อและข้อมูลติดต่อ'});const o=await createOrder(input);return json(res,201,{...o,inventoryReserved:true})}
const om=u.pathname.match(/^\/api\/orders\/([^/]+)$/);if(om&&req.method==='GET'){const o=await getOrder(decodeURIComponent(om[1]));if(!o)return json(res,404,{error:'ไม่พบออเดอร์'});const {customer,items,...pub}=o;return json(res,200,pub)}
if(u.pathname.startsWith('/api/admin/')&&!isAdmin(req))return json(res,401,{error:'unauthorized'});
if(u.pathname==='/api/admin/shop'&&req.method==='GET')return json(res,200,await shop());
if(u.pathname==='/api/admin/shop'&&req.method==='PUT'){const b=await body(req),s=await shop(),next={...s,...b,shippingFee:Math.max(0,n(b.shippingFee,s.shippingFee)),freeShippingMin:Math.max(0,n(b.freeShippingMin,s.freeShippingMin)),wholesaleMinTotal:Math.max(1,Math.floor(n(b.wholesaleMinTotal,s.wholesaleMinTotal)))};return json(res,200,await saveSetting('shop',next))}
if(u.pathname==='/api/admin/filter-config'&&req.method==='GET')return json(res,200,await setting('filter_config',DEFAULT_FILTERS));
if(u.pathname==='/api/admin/filter-config'&&req.method==='PUT'){const cfg=normalizeGroups(await body(req));return json(res,200,await saveSetting('filter_config',cfg))}
if(u.pathname==='/api/admin/products'&&req.method==='GET')return json(res,200,await products());
if(u.pathname==='/api/admin/products/bulk-prices'&&req.method==='PUT')return json(res,200,await bulkPrices(await body(req)));
if(u.pathname==='/api/admin/products'&&req.method==='POST'){const b=await body(req);let id=String(b.id||'').trim();if(!id)id='p'+crypto.randomBytes(4).toString('hex');if((await productById(id))?.id)return json(res,409,{error:'รหัสสินค้านี้มีอยู่แล้ว'});const p=cleanProduct({...b,id,image:b.image||'',active:b.active!==false});return json(res,201,await saveProduct(p))}
const pm=u.pathname.match(/^\/api\/admin\/products\/([^/]+)$/);if(pm&&req.method==='PATCH'){const id=decodeURIComponent(pm[1]),old=await productById(id);if(!old?.id)return json(res,404,{error:'ไม่พบสินค้า'});const b=await body(req),next=cleanProduct({...old,...b,id,prices:{...old.prices,...(b.prices||{})},stock:{...old.stock,...(b.stock||{})},tags:b.tags===undefined?old.tags:b.tags});return json(res,200,await saveProduct(next))}
if(pm&&req.method==='DELETE')return json(res,200,await deleteProduct(decodeURIComponent(pm[1])));
const pim=u.pathname.match(/^\/api\/admin\/products\/([^/]+)\/image$/);if(pim&&req.method==='POST'){const id=decodeURIComponent(pim[1]),b=await body(req);return json(res,200,await saveProductImage(id,String(b.mime||''),String(b.data||'')))}
if(u.pathname==='/api/admin/orders'&&req.method==='GET')return json(res,200,await listOrders());
const sm=u.pathname.match(/^\/api\/admin\/orders\/([^/]+)\/status$/);if(sm&&req.method==='PATCH'){const b=await body(req);return json(res,200,await setStatus(decodeURIComponent(sm[1]),String(b.status||'')))}
return json(res,404,{error:'not found'});
}catch(e){console.error(e);return json(res,e.status||500,{error:e.message||'server error'})}});
server.listen(PORT,()=>console.log(`Order Catalog API v2.5 on ${PORT}; storage=${pool?'postgres':'memory'}`));
