(function(){
  const API='https://order-catalog-api-v22.onrender.com';
  const MAX_QTY=100;
  const $v=s=>document.querySelector(s);
  const totalCartQty=()=>cart.reduce((a,b)=>a+Math.max(1,Number(b.qty)||1),0);
  const wholesaleMin=()=>Math.max(1,Number(shop.wholesaleMinTotal||20));
  const isWholesale=q=>Number(q)>=wholesaleMin();
  function tierPrice(p,size,orderQty){const pr=p.prices?.[size]||{retail:0,wholesale:0};const wholesale=isWholesale(orderQty);const unit=Number(wholesale?pr.wholesale:pr.retail)||0;return{...pr,unit,type:wholesale?'ส่ง':'ปลีก'}}
  function optionsQty(max=MAX_QTY,value=1){max=Math.max(1,Math.min(MAX_QTY,Number.isFinite(max)?Math.floor(max):MAX_QTY));return Array.from({length:max},(_,i)=>`<option value="${i+1}" ${(i+1)===Number(value)?'selected':''}>${i+1}</option>`).join('')}
  function installQtySelect(){const old=$v('#pmQty');if(!old||old.tagName==='SELECT')return;const s=document.createElement('select');s.id='pmQty';s.innerHTML=optionsQty(MAX_QTY,1);old.replaceWith(s);s.onchange=calcProductV24}
  function updateTierBanner(prospective=totalCartQty()){
    let el=$v('#v24Tier');if(!el){el=document.createElement('div');el.id='v24Tier';el.className='v24-tier';const toolbar=$v('.toolbar');if(toolbar)toolbar.insertAdjacentElement('afterend',el)}
    const min=wholesaleMin(),q=Number(prospective)||0;el.innerHTML=isWholesale(q)?`<b>ราคาส่งทำงานแล้ว</b> • จำนวนรวม ${q} ขวด (ขั้นต่ำ ${min})`:`สั่งรวม <b>${q}</b> ขวด • ครบ <b>${min}</b> ขวด รับราคาส่งทั้งออเดอร์`;
    el.classList.toggle('wholesale',isWholesale(q));
  }
  function openProductV24(p){current=p;$v('#pmImg').src=p.image;$v('#pmName').textContent=p.name;$v('#pmSize').innerHTML=p.sizes.map(x=>`<option>${esc(x)}</option>`).join('');$v('#pmCap').innerHTML=p.caps.map(x=>`<option>${esc(x)}</option>`).join('');const available=stockFor(p,p.sizes[0]);$v('#pmQty').innerHTML=optionsQty(Number.isFinite(available)?Math.min(MAX_QTY,available):MAX_QTY,1);$v('#pmQty').value='1';calcProductV24();show('productModal')}
  function calcProductV24(){if(!current)return;const size=$v('#pmSize').value,qty=Math.max(1,Number($v('#pmQty').value)||1),available=stockFor(current,size),prospective=totalCartQty()+qty,pr=tierPrice(current,size,prospective);$v('#pmRetail').textContent=money(pr.retail);$v('#pmWholesale').textContent=money(pr.wholesale);let rule=`ราคาส่งเมื่อจำนวนรวมทั้งออเดอร์ถึง ${wholesaleMin()} ขวด • ตอนนี้ถ้าเพิ่มรายการนี้จะรวม ${prospective} ขวด`;if(current.stockTracked)rule+=` • คงเหลือ ${Number.isFinite(available)?available:0} ชิ้น`;$v('#pmRule').textContent=rule;$v('#pmTotal').textContent=money(pr.unit*qty);const chip=$v('#pmStockChip');if(current.stockTracked){chip.classList.remove('hidden','stock-ok','stock-low','stock-out');const th=Number(current.lowStockThreshold??5);chip.classList.add(available<=0?'stock-out':available<=th?'stock-low':'stock-ok');chip.textContent=available<=0?'สินค้าหมด':`คงเหลือ ${available} ชิ้น`;chip.classList.toggle('soldout-detail',available<=0)}else chip.classList.add('hidden');$v('#addCartBtn').disabled=current.stockTracked&&(available<=0||qty+cartQtyFor(current.id,size)>available);$v('#addCartBtn').textContent=current.stockTracked&&available<=0?'สินค้าหมด':current.stockTracked&&qty+cartQtyFor(current.id,size)>available?'จำนวนเกินสต็อก':isWholesale(prospective)?'เพิ่มลงตะกร้า • ราคาส่ง':'เพิ่มลงตะกร้า';updateTierBanner(prospective)}
  function updateCartV24(){const q=totalCartQty();cart=cart.map(i=>{const p=products.find(x=>x.id===i.productId);if(p){const r=tierPrice(p,i.size,q);Object.assign(i,{unit:r.unit,total:r.unit*i.qty,priceType:r.type})}return i});store(K.cart,cart);$v('#cartCount').textContent=q;$v('#cartTotalMini').textContent=money(cart.reduce((a,b)=>a+b.total,0));updateTierBanner(q)}
  function addCartV24(){const size=$v('#pmSize').value,cap=$v('#pmCap').value,qty=Math.max(1,Number($v('#pmQty').value)||1),available=stockFor(current,size);if(current.stockTracked&&qty+cartQtyFor(current.id,size)>available)return alert(`สินค้า ${size} คงเหลือ ${available} ชิ้น`);cart.push({id:crypto.randomUUID(),productId:current.id,name:current.name,image:current.image,size,cap,qty,unit:0,total:0,priceType:'ปลีก'});updateCartV24();hide('productModal');renderCartV24();show('cartModal')}
  function renderCartV24(){updateCartV24();const w=$v('#cartItems');w.innerHTML='';if(!cart.length)w.innerHTML='<p class="muted-line">ยังไม่มีสินค้าในตะกร้า</p>';for(const i of cart){const p=products.find(x=>x.id===i.productId),available=p?stockFor(p,i.size):Infinity,max=Number.isFinite(available)?Math.max(1,Math.min(MAX_QTY,available)):MAX_QTY;const d=document.createElement('div');d.className='cart-item';d.innerHTML=`<img src="${i.image}"><div><h4>${esc(i.name)}</h4><p>${i.size} • ${i.cap} • ราคาขาย${i.priceType}</p><p>${money(i.unit)} / ชิ้น</p>${p?.stockTracked?`<p class="${available<=Number(p.lowStockThreshold??5)?'stock-low-text':''}">คงเหลือ ${available} ชิ้น</p>`:''}<div class="qty-row"><label>จำนวน</label><select>${optionsQty(max,i.qty)}</select></div><p><b>${money(i.total)}</b></p></div><button class="remove">×</button>`;d.querySelector('.remove').onclick=()=>{cart=cart.filter(x=>x.id!==i.id);updateCartV24();renderCartV24()};d.querySelector('select').onchange=e=>{const q=Math.max(1,Number(e.target.value)||1);if(p?.stockTracked){const other=cartQtyFor(i.productId,i.size,i.id);if(q+other>available){alert(`สินค้า ${i.size} คงเหลือ ${available} ชิ้น`);e.target.value=String(i.qty);return}}i.qty=q;updateCartV24();renderCartV24()};w.appendChild(d)}$v('#grandTotal').textContent=money(cart.reduce((a,b)=>a+b.total,0));const tier=document.createElement('div');tier.className='v24-cart-tier';tier.textContent=isWholesale(totalCartQty())?`✓ จำนวนรวม ${totalCartQty()} ขวด ได้ราคาส่งทั้งออเดอร์`:`จำนวนรวม ${totalCartQty()} ขวด • อีก ${Math.max(0,wholesaleMin()-totalCartQty())} ขวดถึงราคาส่ง`;w.prepend(tier)}
  async function confirmOrderV24(){if(!cart.length)return alert('ยังไม่มีสินค้า');updateCartV24();if(cloud.connected)await refreshCloudProducts();const stockError=validateCartStock();if(stockError)return alert('สต็อกสินค้าเปลี่ยนแปลง กรุณาตรวจสอบตะกร้า\n'+stockError);const name=$v('#cName').value.trim(),contact=$v('#cContact').value.trim();if(!name||!contact)return alert('กรุณากรอกชื่อลูกค้าและข้อมูลติดต่อ');const deliveryMethod=$v('#cDeliveryMethod').value,address=$v('#cAddress').value.trim();if(deliveryMethod==='delivery'&&!address)return alert('กรุณากรอกที่อยู่จัดส่ง');customer={name,contact,address,deliveryMethod,note:$v('#cNote').value.trim()};store(K.customer,customer);lastOrderId=makeOrderId();const subtotal=cart.reduce((a,b)=>a+b.total,0),shippingFee=shippingFeeFor(subtotal,deliveryMethod);const order={id:lastOrderId,createdAt:new Date().toISOString(),customer:{...customer},seller:shop.brand||'',items:cart.map(x=>({...x})),itemCount:totalCartQty(),subtotal,shipping:{method:deliveryMethod,address:deliveryMethod==='delivery'?address:'',fee:shippingFee,carrier:'',trackingNo:''},total:subtotal+shippingFee,status:'pending',paymentStatus:'unpaid',inventoryDeducted:false};let cloudSaved=false;if(cloud.connected){try{const reserved=await window.cloudCatalog.reserveOrder(order);cloudSaved=true;order.inventoryReserved=!!reserved.inventoryReserved;order.inventoryDeducted=!!reserved.inventoryReserved;if(Array.isArray(reserved.items))order.items=reserved.items.map(x=>({...x}));if(Number.isFinite(Number(reserved.itemCount)))order.itemCount=Number(reserved.itemCount);if(Number.isFinite(Number(reserved.subtotal)))order.subtotal=Number(reserved.subtotal);if(Number.isFinite(Number(reserved.total)))order.total=Number(reserved.total);if(reserved.shipping&&Number.isFinite(Number(reserved.shipping.fee)))order.shipping={...order.shipping,...reserved.shipping};if(reserved.pricingTier)order.pricingTier=reserved.pricingTier}catch(e){console.warn(e);await refreshCloudProducts().catch(()=>{});return alert('สั่งซื้อไม่สำเร็จ: '+(e?.message||String(e))+'\nกรุณาตรวจสอบรายการแล้วลองใหม่')}}const localOrders=load('orders_v20',[]);localOrders.unshift(order);store('orders_v20',localOrders.slice(0,200));await drawSummary(order);$v('#orderIdText').textContent=lastOrderId;$v('#orderSavedNotice').textContent=cloudSaved?'ออเดอร์ถูกส่งเข้าระบบร้านและคำนวณราคาจากจำนวนรวมเรียบร้อยแล้ว กรุณาบันทึกภาพนี้ไว้':'บันทึกออเดอร์ในเครื่องแล้ว กรุณาบันทึกภาพนี้ไว้';hide('checkoutModal');show('summaryModal')}
  async function refreshShop(){try{const r=await fetch(API+'/api/shop',{cache:'no-store'});if(r.ok){shop={...shop,...await r.json()};store(K.shop,shop);updateCartV24();updateTierBanner()}}catch(e){console.warn(e)}}
  function install(){installQtySelect();window.openProduct=openProductV24;window.calcProduct=calcProductV24;window.addCart=addCartV24;window.updateCart=updateCartV24;window.renderCart=renderCartV24;window.confirmOrder=confirmOrderV24;const pmSize=$v('#pmSize'),pmQty=$v('#pmQty'),add=$v('#addCartBtn'),cartBtn=$v('#cartBtn'),checkout=$v('#checkoutBtn'),summary=$v('#summaryBtn');if(pmSize)pmSize.onchange=()=>{const av=current?stockFor(current,pmSize.value):Infinity;pmQty.innerHTML=optionsQty(Number.isFinite(av)?Math.min(MAX_QTY,av):MAX_QTY,1);calcProductV24()};if(pmQty)pmQty.onchange=calcProductV24;if(add)add.onclick=addCartV24;if(cartBtn)cartBtn.onclick=()=>{renderCartV24();show('cartModal')};if(checkout)checkout.onclick=()=>{if(!cart.length)return alert('ยังไม่มีสินค้า');renderCartV24();updateShippingPreview();hide('cartModal');show('checkoutModal')};if(summary)summary.onclick=confirmOrderV24;updateCartV24();refreshShop()}
  const style=document.createElement('style');style.textContent=`.v24-tier{background:#f6f7f8;border:1px solid #e5e7eb;border-radius:14px;padding:10px 12px;margin:8px 0 12px;font-size:13px}.v24-tier.wholesale{background:#ecfdf3;border-color:#86efac;color:#166534}.v24-cart-tier{padding:10px 12px;border-radius:12px;background:#f6f7f8;font-weight:800;margin-bottom:10px}.qty-row select{min-width:84px}#pmQty{width:100%}`;document.head.appendChild(style);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,80));else setTimeout(install,80);
})();
