const $=s=>document.querySelector(s);
const money=n=>'฿'+Number(n||0).toLocaleString('th-TH');
const K={catalog:'catalogEdits_v19',cart:'cart_v19',customer:'customer_v19',shop:'shop_v19'};
let products=[],cart=[],current=null,customer={name:'',contact:'',address:'',deliveryMethod:'delivery',note:''},shop={brand:'ORDER CATALOG',sub:'เลือกสินค้า • ขนาด • ฝา • จำนวน',contact:'',shippingFee:50,freeShippingMin:0},cloud={connected:false},lastOrderId='',lastOrderBlob=null;
function load(k,f){try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}}
function store(k,v){localStorage.setItem(k,JSON.stringify(v))}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function show(id){$('#'+id).classList.remove('hidden')} function hide(id){$('#'+id).classList.add('hidden')}
function normalizeProduct(p){return {...p,stockTracked:!!p.stockTracked,stock:{'10ml':Number(p.stock?.['10ml']||0),'30ml':Number(p.stock?.['30ml']||0)},lowStockThreshold:Number(p.lowStockThreshold??5)}}
async function init(){
 const base=(await (await fetch('catalog.json')).json()).map(normalizeProduct); products=load(K.catalog,base).map(normalizeProduct);cart=load(K.cart,[]);customer=load(K.customer,customer);shop=load(K.shop,shop);
 if(window.cloudCatalog){cloud=await window.cloudCatalog.init();if(cloud.connected){try{const [rp,rs]=await Promise.all([window.cloudCatalog.getProducts(),window.cloudCatalog.getShop()]);if(rp.length){products=rp.map(normalizeProduct);store(K.catalog,products)}if(rs){shop={...shop,...rs};store(K.shop,shop)}}catch(e){console.warn(e)}}}
 applyShop();fillCustomer();render();updateCart(); if('serviceWorker'in navigator) navigator.serviceWorker.register('service-worker.js').catch(()=>{});
}
function applyShop(){$('#brandName').textContent=shop.brand||'ORDER CATALOG';$('#brandSub').textContent=shop.sub||'';$('#shopContact').textContent=shop.contact||''}
function fillCustomer(){ $('#cName').value=customer.name||'';$('#cContact').value=customer.contact||'';$('#cAddress').value=customer.address||'';$('#cDeliveryMethod').value=customer.deliveryMethod||'delivery';$('#cNote').value=customer.note||'';updateShippingPreview() }
function active(){const q=$('#searchInput').value.trim().toLowerCase(),sf=$('#sizeFilter').value;return products.filter(p=>p.active!==false&&(!q||p.name.toLowerCase().includes(q))&&(!sf||p.sizes.includes(sf)))}
function priceFor(p,size,qty){const pr=p.prices[size]||{retail:0,wholesale:0};const wholesale=qty>=p.wholesaleMin;const unit=wholesale?pr.wholesale:pr.retail;return{...pr,unit,total:unit*qty,type:wholesale?'ส่ง':'ปลีก'}}
function stockFor(p,size){return p.stockTracked?Math.max(0,Number(p.stock?.[size]||0)):Infinity}
function stockState(p){if(!p.stockTracked)return{cls:'stock-untracked',text:'พร้อมสั่ง'};const vals=(p.sizes||[]).map(s=>stockFor(p,s));const total=vals.reduce((a,b)=>a+b,0),th=Number(p.lowStockThreshold??5);if(total<=0)return{cls:'stock-out',text:'สินค้าหมด'};if(vals.some(v=>v<=th))return{cls:'stock-low',text:'สินค้าใกล้หมด'};return{cls:'stock-ok',text:'มีสินค้า'}}
function render(){const g=$('#productGrid');g.innerHTML='';const list=active();for(const p of list){const min=Math.min(...p.sizes.map(s=>p.prices[s]?.retail||999999)),st=stockState(p),sold=p.stockTracked&&(p.sizes||[]).every(s=>stockFor(p,s)<=0);const d=document.createElement('article');d.className='card'+(sold?' sold-out':'');d.innerHTML=`<img loading="lazy" src="${p.image}" alt="${esc(p.name)}"><div class="card-body"><h3>${esc(p.name)}</h3><div class="meta">${p.sizes.map(s=>`<span class="badge">${esc(s)}</span>`).join('')}</div><span class="stock-state ${st.cls}">${st.text}</span>${sold?'<div class="soldout-message">สินค้าหมด</div>':''}<div class="from">ราคาเริ่มต้น</div><div class="price">${money(min)}</div><button ${sold?'disabled':''}>${sold?'สินค้าหมด':'เลือกสินค้า'}</button></div>`;if(!sold)d.querySelector('button').onclick=()=>openProduct(p);g.appendChild(d)}$('#productCount').textContent=list.length.toLocaleString('th-TH')}
function openProduct(p){current=p;$('#pmImg').src=p.image;$('#pmName').textContent=p.name;$('#pmSize').innerHTML=p.sizes.map(x=>`<option>${esc(x)}</option>`).join('');$('#pmCap').innerHTML=p.caps.map(x=>`<option>${esc(x)}</option>`).join('');$('#pmQty').value=1;calcProduct();show('productModal')}
function calcProduct(){if(!current)return;const size=$('#pmSize').value,qty=Math.max(1,+$('#pmQty').value||1),pr=priceFor(current,size,qty),available=stockFor(current,size);$('#pmRetail').textContent=money(pr.retail);$('#pmWholesale').textContent=money(pr.wholesale);let rule=`ราคาส่งเมื่อสั่งตั้งแต่ ${current.wholesaleMin} ชิ้น/รายการ`;if(current.stockTracked)rule+=` • คงเหลือ ${Number.isFinite(available)?available:0} ชิ้น`;$('#pmRule').textContent=rule;$('#pmTotal').textContent=money(pr.total);const chip=$('#pmStockChip');if(current.stockTracked){chip.classList.remove('hidden','stock-ok','stock-low','stock-out');const th=Number(current.lowStockThreshold??5);chip.classList.add(available<=0?'stock-out':available<=th?'stock-low':'stock-ok');chip.textContent=available<=0?'สินค้าหมด':`คงเหลือ ${available} ชิ้น`;chip.classList.toggle('soldout-detail',available<=0)}else{chip.classList.add('hidden');chip.classList.remove('soldout-detail')}$('#addCartBtn').disabled=current.stockTracked&&(available<=0||qty>available);$('#addCartBtn').textContent=current.stockTracked&&available<=0?'สินค้าหมด':current.stockTracked&&qty>available?'จำนวนเกินสต็อก':'เพิ่มลงตะกร้า'}
function saveCart(){store(K.cart,cart);updateCart()}
function updateCart(){cart=cart.map(i=>{const p=products.find(x=>x.id===i.productId);if(p){const r=priceFor(p,i.size,i.qty);Object.assign(i,{unit:r.unit,total:r.total,priceType:r.type})}return i});store(K.cart,cart);$('#cartCount').textContent=cart.reduce((a,b)=>a+b.qty,0);$('#cartTotalMini').textContent=money(cart.reduce((a,b)=>a+b.total,0))}
function cartQtyFor(productId,size,excludeId=''){return cart.filter(i=>i.id!==excludeId&&i.productId===productId&&i.size===size).reduce((a,b)=>a+b.qty,0)}
function addCart(){const size=$('#pmSize').value,cap=$('#pmCap').value,qty=Math.max(1,+$('#pmQty').value||1),available=stockFor(current,size);if(current.stockTracked&&qty+cartQtyFor(current.id,size)>available)return alert(`สินค้า ${size} คงเหลือ ${available} ชิ้น`);const r=priceFor(current,size,qty);cart.push({id:crypto.randomUUID(),productId:current.id,name:current.name,image:current.image,size,cap,qty,unit:r.unit,total:r.total,priceType:r.type});saveCart();hide('productModal');renderCart();show('cartModal')}
function renderCart(){const w=$('#cartItems');w.innerHTML='';if(!cart.length)w.innerHTML='<p class="muted-line">ยังไม่มีสินค้าในตะกร้า</p>';for(const i of cart){const p=products.find(x=>x.id===i.productId),available=p?stockFor(p,i.size):Infinity;const d=document.createElement('div');d.className='cart-item';d.innerHTML=`<img src="${i.image}"><div><h4>${esc(i.name)}</h4><p>${i.size} • ${i.cap} • ราคาขาย${i.priceType}</p><p>${money(i.unit)} / ชิ้น</p>${p?.stockTracked?`<p class="${available<=Number(p.lowStockThreshold??5)?'stock-low-text':''}">คงเหลือ ${available} ชิ้น</p>`:''}<div class="qty-row"><label>จำนวน</label><input type="number" min="1" ${Number.isFinite(available)?`max="${available}"`:''} value="${i.qty}"></div><p><b>${money(i.total)}</b></p></div><button class="remove">×</button>`;d.querySelector('.remove').onclick=()=>{cart=cart.filter(x=>x.id!==i.id);saveCart();renderCart()};d.querySelector('input').oninput=e=>{let q=Math.max(1,+e.target.value||1);if(p?.stockTracked){const other=cartQtyFor(i.productId,i.size,i.id),max=Math.max(0,available-other);if(q>max){q=max||1;e.target.value=q;alert(`สินค้า ${i.size} คงเหลือ ${available} ชิ้น`)}}i.qty=q;saveCart();renderCart()};w.appendChild(d)}$('#grandTotal').textContent=money(cart.reduce((a,b)=>a+b.total,0))}
function makeOrderId(){const d=new Date();const y=String(d.getFullYear()).slice(-2),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');const rand=crypto.getRandomValues(new Uint32Array(2));const code=(rand[0].toString(36)+rand[1].toString(36)).slice(0,8).toUpperCase();return `OD${y}${m}${day}-${code}`}
function trackingUrl(id=lastOrderId){return new URL(`track.html?id=${encodeURIComponent(id)}`,location.href).href}
function shippingFeeFor(subtotal,method){if(method==='pickup')return 0;const freeMin=Number(shop.freeShippingMin||0);if(freeMin>0&&subtotal>=freeMin)return 0;return Math.max(0,Number(shop.shippingFee||0))}
function updateShippingPreview(){const method=$('#cDeliveryMethod')?.value||'delivery',subtotal=cart.reduce((a,b)=>a+b.total,0),fee=shippingFeeFor(subtotal,method);if($('#deliveryFields'))$('#deliveryFields').classList.toggle('hidden',method==='pickup');if($('#shippingFeeText'))$('#shippingFeeText').textContent=money(fee)}
async function refreshCloudProducts(){if(!cloud.connected)return;try{const rp=await window.cloudCatalog.getProducts();if(rp.length){products=rp.map(normalizeProduct);store(K.catalog,products);render();updateCart()}}catch(e){console.warn(e)}}
function validateCartStock(){for(const i of cart){const p=products.find(x=>x.id===i.productId);if(!p?.stockTracked)continue;const needed=cart.filter(x=>x.productId===i.productId&&x.size===i.size).reduce((a,b)=>a+b.qty,0),available=stockFor(p,i.size);if(needed>available)return `${p.name} ${i.size} คงเหลือ ${available} ชิ้น`; }return ''}
async function confirmOrder(){
  if(!cart.length)return alert('ยังไม่มีสินค้า');
  if(cloud.connected)await refreshCloudProducts();
  const stockError=validateCartStock();
  if(stockError)return alert('สต็อกสินค้าเปลี่ยนแปลง กรุณาตรวจสอบตะกร้า\n'+stockError);
  const name=$('#cName').value.trim(),contact=$('#cContact').value.trim();
  if(!name||!contact)return alert('กรุณากรอกชื่อลูกค้าและข้อมูลติดต่อ');
  const deliveryMethod=$('#cDeliveryMethod').value,address=$('#cAddress').value.trim();
  if(deliveryMethod==='delivery'&&!address)return alert('กรุณากรอกที่อยู่จัดส่ง');
  customer={name,contact,address,deliveryMethod,note:$('#cNote').value.trim()};store(K.customer,customer);
  lastOrderId=makeOrderId();
  const subtotal=cart.reduce((a,b)=>a+b.total,0),shippingFee=shippingFeeFor(subtotal,deliveryMethod),total=subtotal+shippingFee;
  const order={id:lastOrderId,createdAt:new Date().toISOString(),customer:{...customer},seller:shop.brand||'',items:cart.map(x=>({...x})),itemCount:cart.reduce((a,b)=>a+b.qty,0),subtotal,shipping:{method:deliveryMethod,address:deliveryMethod==='delivery'?address:'',fee:shippingFee,carrier:'',trackingNo:''},total,status:'pending',paymentStatus:'unpaid',inventoryDeducted:false};
  let cloudSaved=false;
  if(cloud.connected){
    try{
      const reserved=await window.cloudCatalog.reserveOrder(order);
      cloudSaved=true;
      order.inventoryReserved=!!reserved.inventoryReserved;
      order.inventoryDeducted=!!reserved.inventoryReserved;
      if(Number.isFinite(Number(reserved.total))){
        order.total=Number(reserved.total);
        order.shipping.fee=Math.max(0,order.total-order.subtotal);
      }
    }catch(e){
      console.warn(e);
      await refreshCloudProducts().catch(()=>{});
      return alert('สั่งซื้อไม่สำเร็จ: '+(e?.message||String(e))+'\nกรุณาตรวจสอบรายการแล้วลองใหม่');
    }
  }
  const localOrders=load('orders_v20',[]);
  localOrders.unshift(order);
  store('orders_v20',localOrders.slice(0,200));
  await drawSummary(order);
  $('#orderIdText').textContent=lastOrderId;
  $('#orderSavedNotice').textContent=cloudSaved?'ออเดอร์ถูกส่งเข้าระบบร้านและจองสต็อกเรียบร้อยแล้ว กรุณาบันทึกภาพนี้ไว้':'บันทึกออเดอร์ในเครื่องแล้ว กรุณาบันทึกภาพนี้ไว้';
  hide('checkoutModal');show('summaryModal');
}
async function drawSummary(order){const c=$('#summaryCanvas'),ctx=c.getContext('2d'),W=1200,rowH=210,header=380,footer=200,H=header+rowH*order.items.length+footer;c.width=W;c.height=H;ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);ctx.fillStyle='#111';ctx.font='bold 58px sans-serif';ctx.fillText(shop.brand||'ORDER CATALOG',60,72);ctx.font='bold 34px sans-serif';ctx.fillText(`เลขออเดอร์ ${order.id}`,60,122);ctx.font='26px sans-serif';ctx.fillStyle='#555';ctx.fillText(new Date(order.createdAt).toLocaleString('th-TH'),60,162);ctx.fillStyle='#111';ctx.fillText(`ลูกค้า: ${order.customer.name}`,60,208);ctx.fillText(`ติดต่อ: ${order.customer.contact}`,60,244);ctx.fillText(`รับสินค้า: ${order.shipping?.method==='pickup'?'รับเอง / นัดรับ':'จัดส่งพัสดุ'}`,60,280);if(order.shipping?.method==='delivery'&&order.shipping?.address)wrap(ctx,`ที่อยู่: ${order.shipping.address}`,60,316,W-120,30);if(order.customer.note)wrap(ctx,`หมายเหตุ: ${order.customer.note}`,60,352,W-120,30);let y=header,total=0;for(const i of order.items){total+=i.total;try{const img=await loadImg(i.image);ctx.drawImage(img,60,y-25,160,160)}catch{}ctx.fillStyle='#111';ctx.font='bold 30px sans-serif';wrap(ctx,i.name,250,y+8,560,34);ctx.font='24px sans-serif';ctx.fillStyle='#555';ctx.fillText(`${i.size} • ${i.cap} • ${i.qty} ชิ้น • ${i.priceType}`,250,y+88);ctx.fillText(`${money(i.unit)} / ชิ้น`,250,y+124);ctx.fillStyle='#111';ctx.font='bold 34px sans-serif';ctx.textAlign='right';ctx.fillText(money(i.total),W-60,y+78);ctx.textAlign='left';ctx.strokeStyle='#eee';ctx.beginPath();ctx.moveTo(60,y+150);ctx.lineTo(W-60,y+150);ctx.stroke();y+=rowH}ctx.font='26px sans-serif';ctx.fillStyle='#555';ctx.fillText('ยอดสินค้า',60,H-150);ctx.textAlign='right';ctx.fillText(money(order.subtotal??total),W-60,H-150);ctx.textAlign='left';ctx.fillText('ค่าจัดส่ง',60,H-115);ctx.textAlign='right';ctx.fillText(money(order.shipping?.fee||0),W-60,H-115);ctx.textAlign='left';ctx.fillStyle='#111';ctx.font='bold 44px sans-serif';ctx.fillText('ยอดรวม',60,H-65);ctx.textAlign='right';ctx.fillText(money(order.total),W-60,H-65);ctx.textAlign='left';ctx.font='22px sans-serif';ctx.fillStyle='#666';ctx.fillText(shop.contact||'กรุณาตรวจสอบรายการก่อนชำระเงิน',60,H-45);lastOrderBlob=await new Promise(r=>c.toBlob(r,'image/jpeg',.96))}
function wrap(ctx,t,x,y,max,lh){let line='',yy=y;for(const ch of String(t)){const q=line+ch;if(ctx.measureText(q).width>max&&line){ctx.fillText(line,x,yy);line=ch;yy+=lh}else line=q}ctx.fillText(line,x,yy)}
function loadImg(src){return new Promise((r,j)=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>r(i);i.onerror=j;i.src=src})}
function textSummary(){const subtotal=cart.reduce((a,b)=>a+b.total,0),method=customer.deliveryMethod||'delivery',fee=shippingFeeFor(subtotal,method),total=subtotal+fee;return [`ออเดอร์ ${lastOrderId}`,`ลูกค้า: ${customer.name}`,`ติดต่อ: ${customer.contact}`,`รับสินค้า: ${method==='pickup'?'รับเอง / นัดรับ':'จัดส่งพัสดุ'}`,method==='delivery'&&customer.address?`ที่อยู่: ${customer.address}`:'',...cart.flatMap((i,n)=>[`${n+1}. ${i.name}`,`   ${i.size} / ${i.cap} / ${i.qty} ชิ้น = ${money(i.total)}`]),`ยอดสินค้า ${money(subtotal)}`,`ค่าจัดส่ง ${money(fee)}`,`ยอดรวม ${money(total)}`,customer.note?`หมายเหตุ: ${customer.note}`:'',`ติดตามสถานะ: ${trackingUrl()}`].filter(Boolean).join('\n')}
function openLineShare(){window.open(`https://line.me/R/msg/text/?${encodeURIComponent(textSummary())}`,'_blank','noopener')}
function openTracking(){if(lastOrderId)location.href=`track.html?id=${encodeURIComponent(lastOrderId)}`}
async function uploadSlip(){if(!lastOrderId)return alert('ยังไม่มีเลขออเดอร์');const f=$('#slipInput')?.files?.[0];if(!f)return alert('กรุณาเลือกภาพสลิปก่อน');if(!/^image\/(jpeg|png|webp)$/.test(f.type))return alert('รองรับเฉพาะ JPG, PNG หรือ WEBP');if(f.size>10*1024*1024)return alert('ไฟล์สลิปต้องไม่เกิน 10 MB');if(!cloud.connected)return alert('ระบบ Cloud ยังไม่พร้อม กรุณาติดต่อร้าน');const btn=$('#uploadSlipBtn');btn.disabled=true;btn.textContent='กำลังอัปโหลด...';try{const path=await window.cloudCatalog.uploadPaymentSlip(f,lastOrderId);await window.cloudCatalog.savePaymentSubmission(lastOrderId,{orderId:lastOrderId,slipPath:path,status:'submitted',submittedAt:new Date().toISOString()});const el=$('#paymentStatusText');el.className='payment-status ps-submitted';el.textContent='สถานะการชำระเงิน: ส่งสลิปแล้ว รอร้านตรวจสอบ';$('#slipInput').value='';alert('อัปโหลดสลิปเรียบร้อยแล้ว')}catch(e){alert('อัปโหลดสลิปไม่สำเร็จ: '+e.message)}finally{btn.disabled=false;btn.textContent='อัปโหลดสลิปการโอน'}}
$('#addCartBtn').onclick=addCart;$('#cartBtn').onclick=()=>{renderCart();show('cartModal')};$('#clearCart').onclick=()=>{if(confirm('ล้างรายการทั้งหมด?')){cart=[];saveCart();renderCart()}};$('#checkoutBtn').onclick=()=>{if(!cart.length)return alert('ยังไม่มีสินค้า');hide('cartModal');fillCustomer();show('checkoutModal')};$('#cDeliveryMethod').onchange=updateShippingPreview;$('#summaryBtn').onclick=confirmOrder;$('#pmSize').onchange=calcProduct;$('#pmQty').oninput=calcProduct;$('#searchInput').oninput=render;$('#sizeFilter').onchange=render;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>hide(b.dataset.close));
$('#downloadJpg').onclick=()=>{const a=document.createElement('a');a.download=`${lastOrderId}.jpg`;a.href=$('#summaryCanvas').toDataURL('image/jpeg',.96);a.click()};
$('#shareJpgBtn').onclick=async()=>{if(!lastOrderBlob)return;const file=new File([lastOrderBlob],`${lastOrderId}.jpg`,{type:'image/jpeg'});try{if(navigator.canShare?.({files:[file]}))await navigator.share({title:`ออเดอร์ ${lastOrderId}`,text:`ออเดอร์ ${lastOrderId}`,files:[file]});else alert('อุปกรณ์นี้ไม่รองรับการแชร์ไฟล์โดยตรง กรุณากดบันทึก JPG')}catch(e){if(e.name!=='AbortError')alert('แชร์ไม่สำเร็จ')}};
$('#copyTextBtn').onclick=async()=>{try{await navigator.clipboard.writeText(textSummary());alert('คัดลอกข้อความแล้ว')}catch{alert('คัดลอกไม่สำเร็จ')}};$('#lineShareBtn').onclick=openLineShare;$('#trackOrderBtn').onclick=openTracking;
$('#newOrderBtn').onclick=()=>{cart=[];saveCart();hide('summaryModal');window.scrollTo({top:0,behavior:'smooth'})};$('#uploadSlipBtn').onclick=uploadSlip;
init();
